name: QandA CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

#Linting of the code using pylint
  build:
    runs-on: ubuntu-latest
    name: QandA Linting
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flask pytest
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

#Unit testing - testing each function in the code
  test:
    needs: build
    runs-on: ubuntu-latest
    name: QandA Unit Testing
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest flask
    - name: Test with pytest
      run: |
        pytest

#Deploy the app to Render by calling their deployment process
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy to Render
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.6
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true